import { C, Reveal, SectionLabel, SectionHeading, CodeBlock, CalloutBox, PlainEnglishBox } from "../../src/shared.jsx";
import { P } from "./ui.jsx";

const CODEOWNERS_CODE = `# .github/CODEOWNERS — iOS-Payments SDK
# Format: <pattern>  <owner(s)>
# Last matching rule wins.

# ── Default: architects review everything ────────────────
*                           @AcmeCorp/ios-architects

# ── Core SDK — payments team owns all Swift sources ──────
/Sources/                   @AcmeCorp/payments-ios-team
/Tests/                     @AcmeCorp/payments-ios-team

# ── Security-sensitive paths — architects + security ─────
/Sources/iOSPayments/Auth/  @AcmeCorp/ios-architects \\
                            @AcmeCorp/security-team
/Sources/iOSPayments/Crypto/ @AcmeCorp/security-team

# ── Documentation — docs team reviews .md files ──────────
*.md                        @AcmeCorp/ios-docs-team
/docs/                      @AcmeCorp/ios-docs-team

# ── CI/CD — architects own all workflow files ────────────
/.github/                   @AcmeCorp/ios-architects

# ── CODEOWNERS itself ────────────────────────────────────
/.github/CODEOWNERS         @AcmeCorp/ios-architects`;

const FUNDING_CODE = `# .github/FUNDING.yml
# Displayed as a "Sponsor this project" button
# in the repository sidebar.

# GitHub Sponsors (up to 4 accounts or orgs)
github: [AcmeCorp, giga-khizanishvili]

# External sponsorship platforms
open_collective: acme-corp
ko_fi: acmecorp

# Custom URLs (array, up to 4)
custom:
  - "https://acmecorp.dev/sponsor"
  - "https://opencollective.com/acmecorp"`;

const CITATION_CODE = `cff-version: 1.2.0
message: "If you use this SDK in a publication, cite it."

title: "iOS Payments SDK"
version: "3.2.1"
date-released: 2026-02-01
license: "MIT"

authors:
  - family-names: "Khizanishvili"
    given-names: "Giga"
    affiliation: "Acme Corp"

repository-code: "https://github.com/AcmeCorp/iOS-Payments"
url: "https://docs.acmecorp.dev/ios-payments"

keywords:
  - ios
  - swift
  - payments
  - apple-pay`;

const ITEMS = [
  {
    name: "CODEOWNERS",
    color: P,
    icon: "👤",
    lookups: [".github/CODEOWNERS", "CODEOWNERS", "docs/CODEOWNERS"],
    tagline: "Automatic review requests based on who owns what code",
    idea: "Maps file patterns to GitHub users or teams. When a PR touches any file matching a pattern, GitHub automatically requests a review from the owner — no manual assignment needed. The last matching rule wins, so you can start broad and narrow down. CODEOWNERS itself should be owned by architects to prevent someone quietly removing themselves as a required reviewer.",
    junior: "Imagine a map that says 'whenever someone changes a payment file, automatically ask the payments team to review it.' That's CODEOWNERS — GitHub reads this file and sends review requests for you.",
    note: "Covered in full detail in the GitHub Access Strategy presentation.",
    code: CODEOWNERS_CODE,
    filename: ".github/CODEOWNERS",
    highlights: [6, 9, 10, 12, 13, 14, 15, 17, 18, 20, 22],
  },
  {
    name: "FUNDING.yml",
    color: C.yellow,
    icon: "💛",
    lookups: [".github/FUNDING.yml"],
    tagline: "The sponsor button in your repository sidebar",
    idea: "Once configured, GitHub shows a prominent 'Sponsor this project' button in the sidebar. Clicking it displays all configured platforms — GitHub Sponsors, Open Collective, Ko-fi, and custom URLs. This file has no root or docs/ fallback — it must live in .github/.",
    junior: "This file adds a 'Sponsor' heart button to your GitHub repo's sidebar. Anyone visiting can click it to financially support the project through whatever platform you configure.",
    note: "Supported platforms: github, patreon, ko_fi, tidelift, liberapay, issuehunt, otechie, lfx_crowdfunding, open_collective, custom.",
    code: FUNDING_CODE,
    filename: ".github/FUNDING.yml",
    highlights: [6, 9, 10, 13, 14],
  },
  {
    name: "CITATION.cff",
    color: C.blue,
    icon: "📖",
    lookups: [".github/CITATION.cff", "CITATION.cff"],
    tagline: "How to cite this project in academic publications",
    idea: "YAML metadata in the Citation File Format. GitHub parses it and renders a 'Cite this repository' button in the sidebar, generating auto-formatted BibTeX and APA citations. Most useful for SDKs and tools used in academic or research contexts.",
    junior: "If someone writes a research paper using your SDK, this file tells them how to properly credit it — like an academic footnote, but auto-generated by GitHub as BibTeX or APA format.",
    note: "Primarily relevant for open-source libraries used in research or published in academic contexts.",
    code: CITATION_CODE,
    filename: "CITATION.cff",
    highlights: [5, 6, 9, 10, 11, 12],
  },
];

export function ExtrasSection() {
  return (
    <section id="s-extras" style={{ background: C.surface, borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}`, padding: "96px 48px" }}>
      <div style={{ maxWidth: 1100, margin: "0 auto" }}>
        <Reveal>
          <SectionLabel color={P}>OWNERSHIP & MORE</SectionLabel>
          <SectionHeading sub="Three more recognized files — who reviews code, how to fund the project, and how to cite it. iOS SDK examples for each.">
            CODEOWNERS, Funding & Citation
          </SectionHeading>
        </Reveal>

        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
          {ITEMS.map((item, i) => (
            <Reveal key={item.name} delay={i * 0.12}>
              <div style={{ background: C.bg, border: `1px solid ${item.color}25`, borderLeft: `3px solid ${item.color}`, borderRadius: 14, overflow: "hidden" }}>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1.15fr" }}>
                  <div style={{ padding: "26px 28px", borderRight: `1px solid ${C.border}`, display: "flex", flexDirection: "column", gap: 14 }}>
                    <div>
                      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                        <span style={{ fontSize: 20 }}>{item.icon}</span>
                        <code style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 14, color: item.color }}>{item.name}</code>
                      </div>
                      <div style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 12.5, color: C.muted }}>{item.tagline}</div>
                    </div>

                    <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 13.5, color: C.muted, lineHeight: 1.8, margin: 0 }}>{item.idea}</p>

                    <PlainEnglishBox color={item.color}>{item.junior}</PlainEnglishBox>

                    <div>
                      <div style={{ fontFamily: "'Syne', sans-serif", fontWeight: 700, fontSize: 10, color: C.muted, letterSpacing: "0.12em", marginBottom: 6 }}>LOOKUP PATH</div>
                      {item.lookups.map((l, li) => (
                        <div key={l} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: li === 0 ? item.color : C.subtle, padding: "3px 0", display: "flex", alignItems: "center", gap: 6 }}>
                          <span style={{ color: li === 0 ? item.color : C.subtle }}>{li === 0 ? "✓" : "×"}</span>
                          {l}
                        </div>
                      ))}
                    </div>

                    {item.note && (
                      <div style={{ padding: "10px 13px", background: C.surface, borderRadius: 8, border: `1px solid ${C.border}` }}>
                        <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 12, color: C.muted }}>{item.note}</span>
                      </div>
                    )}
                  </div>

                  <div style={{ padding: "24px 26px" }}>
                    <CodeBlock filename={item.filename} highlights={item.highlights}>{item.code}</CodeBlock>
                  </div>
                </div>
              </div>
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.45}>
          <div style={{ marginTop: 20 }}>
            <CalloutBox color={P} label="OWN YOUR CODEOWNERS FILE" icon="🔒">
              Always add <code style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 13, color: P }}>/.github/CODEOWNERS @org/ios-architects</code> as the last rule in CODEOWNERS. This means architects must approve any change to the file itself — preventing anyone from silently removing their own required review or editing ownership rules without oversight.
            </CalloutBox>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
