import { C, Reveal, SectionLabel, SectionHeading, CodeBlock, CalloutBox, InfoCard, CheckItem } from "../../shared.tsx";
import { P } from "./ui.tsx";

export function CodeConnectSection() {
    return (
        <section id="s-code-connect" style={{ padding: "96px 48px" }}>
            <div style={{ maxWidth: 1200, margin: "0 auto" }}>
                <Reveal>
                    <SectionLabel color={C.purple}>BUILDING BLOCK 1</SectionLabel>
                    <SectionHeading sub="Figma Code Connect maps every S.I.N.S. design-system component to its real SwiftUI initializer. When a designer hovers a Button in Dev Mode, they see the exact call site we&apos;ll use in code.">
                        Code Connect — the Figma ↔ Swift bridge
                    </SectionHeading>
                </Reveal>

                <div style={{ display: "grid", gridTemplateColumns: "1.15fr 1fr", gap: 28, marginTop: 28 }}>
                    <Reveal delay={0}>
                        <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: "18px 20px" }}>
                            <div style={{ fontFamily: "'Syne', sans-serif", fontWeight: 700, fontSize: 11, color: C.purple, letterSpacing: "0.12em", marginBottom: 12 }}>
                                GENERATED <code>.figma.ts</code> TEMPLATE
                            </div>
                            <CodeBlock filename="Autogenerated/Button/ButtonPrimary.figma.ts">{`// url=https://www.figma.com/design/.../SINS?node-id=7-38
// component=StandardButton
// source=github.com/SpaceBank/iOS-Space-Core-UI-V2/...
import figma from "figma"

const i = figma.selectedInstance
const label = i.getString("✍️ Label")
const isLoading = i.getBoolean("Loading")
const style = i.getEnum("Style", { Primary: ".primary", ... })

export default {
    id: "ButtonPrimary",
    example: figma.code\`StandardButton(
        parameters: .init(
            style: \${style},
            text: \${swiftString(label)},
            isLoading: \${isLoading}
        )
    )\`,
}`}</CodeBlock>
                        </div>
                    </Reveal>

                    <Reveal delay={0.1}>
                        <InfoCard icon="🔁" title="How it flows end-to-end" color={C.purple} tag="4 STEPS">
                            <CheckItem active>Designer edits a S.I.N.S. component in Figma</CheckItem>
                            <CheckItem active><strong>npm run generate</strong> emits <code>.figma.ts</code> from a registry/spec</CheckItem>
                            <CheckItem active><strong>npx figma connect publish</strong> uploads mappings</CheckItem>
                            <CheckItem active>Designers + MCP clients see real Swift snippets in Dev Mode</CheckItem>
                        </InfoCard>
                    </Reveal>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16, marginTop: 24 }}>
                    <Reveal delay={0.2}>
                        <InfoCard color={C.purple} title="116" tag="MAPPING FILES">
                            <div style={{ color: C.muted, fontSize: 12, lineHeight: 1.55 }}>One per Figma component family. Buttons alone have 13 variants — IconButton, ActionButton, StandardButton × {"{"}Primary, Secondary, Tertiary, Plain{"}"}.</div>
                        </InfoCard>
                    </Reveal>
                    <Reveal delay={0.26}>
                        <InfoCard color={C.purple} title="15" tag="SPEC ENGINE">
                            <div style={{ color: C.muted, fontSize: 12, lineHeight: 1.55 }}>Declarative <code>ComponentSpec</code> entries that compose nested child instances. The rest live in imperative per-folder definitions.</div>
                        </InfoCard>
                    </Reveal>
                    <Reveal delay={0.32}>
                        <InfoCard color={C.purple} title="0" tag="HAND-EDITED">
                            <div style={{ color: C.muted, fontSize: 12, lineHeight: 1.55 }}>Nothing under <code>Autogenerated/</code> is ever hand-edited. Every change goes through the generator, caught by a pre-commit hook.</div>
                        </InfoCard>
                    </Reveal>
                </div>

                <Reveal delay={0.4}>
                    <div style={{ marginTop: 22 }}>
                        <CalloutBox color={C.purple} icon="💡" label="WHY THIS MATTERS">
                            Without Code Connect, an LLM guessing the Swift API is <strong>wrong ~40% of the time</strong> — wrong enum case, wrong nested type, wrong binding. With Code Connect, the MCP response carries the exact initializer. The View generator just transcribes it.
                        </CalloutBox>
                    </div>
                </Reveal>
            </div>
        </section>
    );
}
