import { C, Reveal, SectionLabel, SectionHeading } from "../../shared.tsx";
import { P, DoDontCard } from "./ui.tsx";

export function DoDontSection() {
    return (
        <section id="s-do-dont" style={{ padding: "96px 48px" }}>
            <div style={{ maxWidth: 1200, margin: "0 auto" }}>
                <Reveal>
                    <SectionLabel color={C.yellow}>OPERATING MANUAL</SectionLabel>
                    <SectionHeading sub="Every rule here came from a real run that went sideways. Follow them and the pipeline does what it says on the tin.">
                        Do&apos;s &amp; Don&apos;ts
                    </SectionHeading>
                </Reveal>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginTop: 28 }}>
                    <Reveal delay={0}>
                        <DoDontCard
                            kind="do"
                            title="Paste the screen node, not a child leaf"
                            bullets={[
                                "The pre-flight refuses nodes < 320×568 or with < 2 children",
                                "A single button node has no state variants to scan",
                                "Sibling-frame scan for Loading/Empty/Error only works on screen frames",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.06}>
                        <DoDontCard
                            kind="dont"
                            title="Hand-edit files under Autogenerated/"
                            bullets={[
                                "Pre-commit hook reverts them and fails the commit",
                                "Edit the spec at _generator/registry/<Name>.ts instead",
                                "Or the imperative def at _generator/components/<folder>.ts",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.12}>
                        <DoDontCard
                            kind="do"
                            title="Open the multi-root workspace"
                            bullets={[
                                "code ios-space.code-workspace",
                                "Lets Copilot see prompts + agents from BOTH repos",
                                "Single-folder opens only see that repo's .github/",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.18}>
                        <DoDontCard
                            kind="dont"
                            title="Run /figma-to-screen on master or main"
                            bullets={[
                                "Phase 7.5 refuses to commit on master/main",
                                "You'll be blocked mid-run — create a feature branch first",
                                "Branch naming: feature/ABC-123_description",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.24}>
                        <DoDontCard
                            kind="do"
                            title="Trust Code Connect — don't re-check from the screenshot"
                            bullets={[
                                "If MCP returned a Swift snippet, transcribe it exactly",
                                "Don't re-invent the init signature from the visual",
                                "Use /component-lookup only when Code Connect is missing",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.3}>
                        <DoDontCard
                            kind="dont"
                            title="Hardcode hex / px / font — call a token"
                            bullets={[
                                "/token-lookup resolves everything in DesignSystem.*",
                                "If no accessor exists, flag it as MISSING to design",
                                "Never ship .foregroundColor(Color(hex: \"#111827\"))",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.36}>
                        <DoDontCard
                            kind="do"
                            title="Review what /figma-to-screen wrote before merging"
                            bullets={[
                                "The session log lists every touched file",
                                "@figma-review output lives in the same log",
                                "ViewModel TODOs mark business-logic placeholders clearly",
                            ]}
                        />
                    </Reveal>
                    <Reveal delay={0.42}>
                        <DoDontCard
                            kind="dont"
                            title="Skip Phase 6 with 'view looks fine' prose"
                            bullets={[
                                "check-figma-review-skip.mjs is code-proved",
                                "Only two legal skip reasons: view unchanged / tool unavailable",
                                "Prose rationale does not override exit code",
                            ]}
                        />
                    </Reveal>
                </div>
            </div>
        </section>
    );
}
