import { C, Reveal, SectionLabel, SectionHeading, CalloutBox } from "../../shared.tsx";
import { P, GateRow } from "./ui.tsx";

const GATES: Array<{ number: number; title: string; tier: "T1" | "T2"; description: string }> = [
    { number: 1, title: "Swift build",              tier: "T1", description: "Generated files compile cleanly in the target module. No red squigglies, no unresolved symbols." },
    { number: 2, title: "SwiftLint --strict",        tier: "T1", description: "Zero violations on every generated file. Trailing commas, import order, member rules — all enforced." },
    { number: 3, title: "Import topology",           tier: "T1", description: "Presentation imports Domain. Domain imports nothing feature-facing. Data maps across. Enforced." },
    { number: 4, title: "DI chain integrity",        tier: "T1", description: "Screen DI → Domain DI → Data DI chain links up. Every Factory call resolves to a registered binding." },
    { number: 5, title: "Localizable coverage",       tier: "T2", description: "New L10n keys landed in en + parallel placeholders in ru / uz. Missing translations warn, don't block." },
    { number: 6, title: "SwiftGen freshness",         tier: "T2", description: "Autogenerated Strings.swift contains the new keys. Stale generator = warning, not a pipeline halt." },
    { number: 7, title: "Copyright & file headers",    tier: "T2", description: "Standard header present. Missing headers warn so devs can batch-fix at commit time." },
];

export function GatesSection() {
    return (
        <section id="s-gates" style={{ background: C.surface, borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}`, padding: "96px 48px" }}>
            <div style={{ maxWidth: 1100, margin: "0 auto" }}>
                <Reveal>
                    <SectionLabel color={P}>VERIFICATION GATES</SectionLabel>
                    <SectionHeading sub="Seven gates, two tiers. T1 is correctness — the pipeline stops. T2 is follow-up — the developer finishes it in the same PR.">
                        How the screen-verifier decides what to fail
                    </SectionHeading>
                </Reveal>

                <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 12, marginBottom: 28 }}>
                    {GATES.map((gate, i) => (
                        <GateRow
                            key={gate.number}
                            number={gate.number}
                            title={gate.title}
                            tier={gate.tier}
                            description={gate.description}
                            delay={i * 0.05}
                        />
                    ))}
                </div>

                <Reveal delay={0.4}>
                    <CalloutBox color={C.yellow} icon="💡" label="WHY TWO TIERS">
                        Pre-tiering, one missing Russian translation would halt a run that had otherwise scaffolded a perfect screen.
                        Tiering respects developer time: the pipeline blocks only when the output would be unshippable, and warns when
                        the work is clearly finish-at-PR-time.
                    </CalloutBox>
                </Reveal>
            </div>
        </section>
    );
}
